import { rollSkillCheck, contestedRoll, sendSkillRollToChat, sendContestedRollToChat, rollResourceRegen } from '../helpers/dice.mjs';
import { openLootboxTier } from '../helpers/lootbox.mjs';

/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class dccworldActor extends Actor {
  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  prepareBaseData() {
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't 
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    const actorData = this;
    const flags = actorData.flags.dungeoncrawlerworld || {};
  }

  /**
   * 
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic 
   * approach is useful when you have actors & items that share a parent Document, 
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...this.system.getRollData?.() ?? null };
  }

  /**
   * Convert the actor document to a plain object.
   *
   * The built in `toObject()` method will ignore derived data when using Data Models.
   * This additional method will instead use the spread operator to return a simplified
   * version of the data.
   *
   * @returns {object} Plain object either via deepClone or the spread operator.
   */
  toPlainObject() {
    const result = {...this};

    // Simplify system data.
    result.system = this.system.toPlainObject();

    // Add items.
    result.items = this.items?.size > 0 ? this.items.contents : [];

    // Add effects.
    result.effects = this.effects?.size > 0 ? this.effects.contents : [];

    // Add derived data references
    if (this.system.raceItem) {
      result.system.raceItem = this.system.raceItem;
    }
    if (this.system.classItem) {
      result.system.classItem = this.system.classItem;
    }

    return result;
  }

  /**
   * Roll a skill check for this actor
   * @param {string} skillUuid - The UUID of the skill to roll
   * @param {Object} options - Additional options for the roll
   * @param {number} options.customLevel - Optional custom skill level to roll at (must be <= actual level)
   * @param {number} options.customEffort - Optional custom effort cost (for weapon attacks)
   * @returns {Promise<Object>} The roll result
   */
  async rollSkill(skillUuid, options = {}) {
    // Only characters have skills
    if (this.type !== 'character') {
      ui.notifications.warn("Only characters can use skill checks.");
      return null;
    }

    const skill = this.system.getSkill(skillUuid);
    if (!skill) {
      ui.notifications.error(`Skill "${skillUuid}" not found.`);
      return null;
    }

    // Check if skill is usable (either has a skill item OR is granted by equipped items)
    if (!skill.id && !skill.sources?.some(s => s.type !== 'skill')) {
      ui.notifications.warn(`Skill "${skill.name}" is not available. Add the skill item or equip an item that grants it.`);
      return null;
    }

    // Determine the level to roll at
    const rollLevel = options.customLevel ? Math.min(options.customLevel, skill.level) : skill.level;
    const isMaxLevel = rollLevel === skill.level;

    // Calculate effort cost from equipped weapons that grant this skill
    let equippedWeaponEffort = 0;
    const equippedWeapons = this.items.filter(i =>
      i.type === 'weapon' && i.system?.equipped === true
    );

    for (const weapon of equippedWeapons) {
      const grantedSkills = weapon.system?.grantedSkills || [];
      // Check if this weapon grants the skill being rolled (compare by skill name)
      for (const gs of grantedSkills) {
        const grantedSkill = this.system.getSkill(gs.skillUuid);
        if (grantedSkill && grantedSkill.name === skill.name) {
          equippedWeaponEffort += (weapon.system?.effort || 0);
          break; // Only count this weapon once per skill
        }
      }
    }

    // Total effort cost = sum of equipped weapon efforts × number of dice rolled
    // Use customEffort if explicitly provided, otherwise calculate from weapons or use skill effort
    const effortCost = options.customEffort !== undefined
      ? options.customEffort
      : (equippedWeaponEffort > 0 ? equippedWeaponEffort * rollLevel : (skill.effort || 0));

    // Check if character has enough stamina
    if (effortCost > 0 && this.system.stamina.value < effortCost) {
      ui.notifications.warn(`Not enough stamina! Need ${effortCost}, have ${this.system.stamina.value}.`);
      return null;
    }

    // LUK is added directly to every roll on top of the skill's own stat modifier.
    const statModifier = this.system.getSkillStatModifier(skill) + (this.system.luck?.total || 0);

    // Only base skill item dice count for level-up.
    // Level 0: pass 0 so dice.mjs uses the maximum die result instead.
    const improvementDice = skill.baseLevel ?? 0;

    const rollResult = await rollSkillCheck({
      skillLevel: rollLevel,
      statModifier,
      skillName: skill.name,
      actor: this,
      improvementDice
    });

    // Deduct stamina after successful roll
    if (effortCost > 0) {
      const newStamina = Math.max(0, this.system.stamina.value - effortCost);
      await this.update({ 'system.stamina.value': newStamina });
      if (effortCost > 0) {
        ui.notifications.info(`-${effortCost} Stamina (${newStamina}/${this.system.stamina.max})`);
      }
    }

    // Send to chat unless explicitly disabled
    if (options.sendToChat !== false) {
      await sendSkillRollToChat(rollResult, {
        ...options.chatOptions,
        effortCost
      });
    }

    // Check for skill improvement (all 6s) - only if rolled at max level
    if (rollResult.allSixes && isMaxLevel && options.checkImprovement !== false) {
      await this._promptSkillImprovement(skill);
    }

    return rollResult;
  }

  /**
   * Perform a contested roll between this actor and another
   * @param {string} attackSkillUuid - This actor's skill UUID
   * @param {Actor} defender - The defending actor
   * @param {string} defenseSkillUuid - Defender's skill UUID
   * @param {Object} options - Additional options
   * @returns {Promise<Object>} The contest result
   */
  async rollContested(attackSkillUuid, defender, defenseSkillUuid, options = {}) {
    if (this.type !== 'character' || defender.type !== 'character') {
      ui.notifications.warn("Only characters can use contested rolls.");
      return null;
    }

    const attackSkill = this.system.getSkill(attackSkillUuid);
    const defenseSkill = defender.system.getSkill(defenseSkillUuid);

    if (!attackSkill || !defenseSkill) {
      ui.notifications.error("One or both skills not found.");
      return null;
    }

    if (!attackSkill.id || !defenseSkill.id) {
      ui.notifications.warn("One or both skill items not found.");
      return null;
    }

    const contestResult = await contestedRoll(
      {
        skillLevel: attackSkill.level,
        statModifier: this.system.getSkillStatModifier(attackSkill) + (this.system.luck?.total || 0),
        skillName: attackSkill.name,
        actor: this
      },
      {
        skillLevel: defenseSkill.level,
        statModifier: defender.system.getSkillStatModifier(defenseSkill) + (defender.system.luck?.total || 0),
        skillName: defenseSkill.name,
        actor: defender
      }
    );

    // Send to chat unless explicitly disabled
    if (options.sendToChat !== false) {
      await sendContestedRollToChat(contestResult, options.chatOptions);
    }

    // Apply damage if this is an attack
    if (options.isAttack && contestResult.attackerWins) {
      await defender.applyDamage(contestResult.difference);
    }

    // Award failure XP (1 XP per failed roll)
    if (this.type === 'character' && !contestResult.attackerWins && !contestResult.tie) {
      await this._awardFailureXP(1);
    }
    if (defender.type === 'character' && contestResult.attackerWins) {
      await defender._awardFailureXP(1);
    }

    // Check for skill improvements
    if (options.checkImprovement !== false) {
      if (contestResult.attackRoll.allSixes) {
        await this._promptSkillImprovement(attackSkill);
      }
      if (contestResult.defenseRoll.allSixes) {
        await defender._promptSkillImprovement(defenseSkill);
      }
    }

    return contestResult;
  }

  /**
   * Apply damage to this actor
   * @param {number} amount - Amount of damage to apply
   * @returns {Promise<Actor>} Updated actor
   */
  async applyDamage(amount) {
    const currentHP = this.system.hp.value;
    const newHP = Math.max(0, currentHP - amount);

    await this.update({ 'system.hp.value': newHP });

    ui.notifications.info(`${this.name} takes ${amount} damage! (${newHP}/${this.system.hp.max} HP)`);

    return this;
  }

  /**
   * Prompt the user about skill improvement
   * @param {Object} skill - The aggregated skill object that can be improved
   * @private
   */
  async _promptSkillImprovement(skill) {
    // Check if skill has multiple sources (skill item + granted from other items)
    const hasSkillItem = skill.sources && skill.sources.some(s => s.type === 'skill');

    if (!hasSkillItem) {
      // No skill item on character - prompt to create it first
      return this._createSkillItemDialog(skill);
    }

    // For skills with items, offer choice to improve or create new
    return this._skillImprovementChoiceDialog(skill);
  }

  /**
   * Show dialog to create a skill item for an aggregated skill
   * @param {Object} skill - The aggregated skill object
   * @private
   */
  async _createSkillItemDialog(skill) {
    new Dialog({
      title: "⚡ Skill Breakthrough!",
      content: `
        <p>You rolled all 6s with <strong>${skill.name}</strong>!</p>
        <p>This skill is granted by items but you don't have the skill item yet.</p>
        <p>Would you like to create the skill item and improve it?</p>
      `,
      buttons: {
        create: {
          icon: '<i class="fas fa-star"></i>',
          label: "Create & Improve",
          callback: async () => {
            // Create new skill item at level 1 (will be boosted by granted skills)
            const skillItemData = {
              name: skill.name,
              type: 'skill',
              system: {
                level: 1,
                category: skill.category || 'general',
                relatedStat: skill.relatedStat || null,
                effort: skill.effort || 0,
                description: skill.description || ''
              }
            };

            const skillItem = await Item.create(skillItemData, { parent: this });

            // Now improve it by 1 level
            const newLevel = (skillItem.system.level || 0) + 1;
            await skillItem.update({ 'system.level': newLevel });

            ui.notifications.info(`⚡ Created and improved ${skill.name} to Level ${newLevel}!`);
          }
        },
        cancel: {
          icon: '<i class="fas fa-times"></i>',
          label: "Cancel"
        }
      },
      default: "create"
    }).render(true);
  }

  /**
   * Show dialog to confirm improving a skill that already has an owned skill item.
   * Skills only ever improve or get materialized from a grant (see _createSkillItemDialog) -
   * there's no "invent a new skill" path here; new skills only ever come from race/class/
   * item/feat grants (see Rules/Skills/Skill Acquisition.md).
   * @param {Object} skill - The skill that can be improved
   * @private
   */
  async _skillImprovementChoiceDialog(skill) {
    new Dialog({
      title: "⚡ Skill Mastery!",
      content: `
        <p>You rolled all 6s with <strong>${skill.name} (Level ${skill.level})</strong>!</p>
        <p>Improve ${skill.name} to Level ${skill.sources[0].level + 1}?</p>
      `,
      buttons: {
        improve: {
          icon: '<i class="fas fa-arrow-up"></i>',
          label: "Improve Skill",
          callback: async () => {
            // Find the skill item on this actor
            const skillItem = this.items.get(skill.id);
            if (!skillItem) {
              ui.notifications.warn("Skill item not found!");
              return;
            }

            const newLevel = (skillItem.system.level || 0) + 1;
            await skillItem.update({ 'system.level': newLevel });
            ui.notifications.info(`⚡ ${skill.name} improved to Level ${newLevel}!`);
          }
        },
        cancel: {
          icon: '<i class="fas fa-times"></i>',
          label: "Decide Later"
        }
      },
      default: "improve"
    }).render(true);
  }

  /**
   * Level up this character by one level, locking in this level's HP/Stamina/Mana
   * gain using today's rates (class values, or CON/INT modifier if no class is
   * equipped). Once locked in, a later ability score change won't retroactively
   * alter the amount gained at this or any earlier level.
   *
   * Requires banked XP to meet the current level's threshold (300 * level); the
   * excess carries over toward the next level rather than being reset to 0.
   *
   * Any earlier levels that predate this tracking (or were reached by editing the
   * Level field by hand) are backfilled at today's rates the first time this runs,
   * so they stop drifting with future stat changes too.
   */
  async levelUp() {
    if (this.type !== 'character') return;

    const currentXP = this.system.attributes.xp.value || 0;
    const neededXP = this.system.attributes.xp.max || 0;
    if (currentXP < neededXP) {
      ui.notifications.warn(`Not enough XP to level up! Need ${neededXP}, have ${currentXP}.`);
      return;
    }

    const currentLevel = this.system.attributes.level.value;
    const newLevel = currentLevel + 1;
    const { hpPerLevel, staminaPerLevel, manaPerLevel } = this.system.currentResourceRates;

    const hpGains = (this.system.hp.gainedByLevel || []).slice(0, currentLevel - 1);
    const staminaGains = (this.system.stamina.gainedByLevel || []).slice(0, currentLevel - 1);
    const manaGains = (this.system.mana.gainedByLevel || []).slice(0, currentLevel - 1);

    while (hpGains.length < currentLevel - 1) hpGains.push(hpPerLevel);
    while (staminaGains.length < currentLevel - 1) staminaGains.push(staminaPerLevel);
    while (manaGains.length < currentLevel - 1) manaGains.push(manaPerLevel);

    hpGains.push(hpPerLevel);
    staminaGains.push(staminaPerLevel);
    manaGains.push(manaPerLevel);

    await this.update({
      'system.attributes.level.value': newLevel,
      'system.hp.gainedByLevel': hpGains,
      'system.stamina.gainedByLevel': staminaGains,
      'system.mana.gainedByLevel': manaGains,
      'system.hp.value': this.system.hp.value + hpPerLevel,
      'system.stamina.value': this.system.stamina.value + staminaPerLevel,
      'system.mana.value': this.system.mana.value + manaPerLevel,
      'system.attributes.xp.value': currentXP - neededXP,
    });

    ui.notifications.info(`${this.name} reached Level ${newLevel}! +${hpPerLevel} HP, +${staminaPerLevel} Stamina, +${manaPerLevel} Mana`);

    // Every level grants 3 stat increase points to spend (see grantStatIncreases/promptStatIncrease).
    await this.grantStatIncreases(3);
  }

  /**
   * Prompt to increase a stat
   */
  async promptStatIncrease() {
    if (this.type !== 'character') return;

    const available = this.system.attributes.statIncreases || 0;

    if (available <= 0) {
      ui.notifications.warn("No stat increases available.");
      return;
    }

    new Dialog({
      title: "Increase Ability Score",
      content: `
        <p>You have <strong>${available}</strong> stat increase${available > 1 ? 's' : ''} available.</p>
        <p>Choose an ability score to increase by 1:</p>
        <form>
          <div class="form-group">
            <label>Ability Score:</label>
            <select name="ability" autofocus>
              <option value="str">STR (${this.system.abilities.str.value})</option>
              <option value="dex">DEX (${this.system.abilities.dex.value})</option>
              <option value="con">CON (${this.system.abilities.con.value})</option>
              <option value="int">INT (${this.system.abilities.int.value})</option>
              <option value="wis">WIS (${this.system.abilities.wis.value})</option>
              <option value="cha">CHA (${this.system.abilities.cha.value})</option>
            </select>
          </div>
        </form>
      `,
      buttons: {
        increase: {
          icon: '<i class="fas fa-arrow-up"></i>',
          label: "Increase",
          callback: async (html) => {
            const formData = new FormData(html[0].querySelector('form'));
            const ability = formData.get('ability');

            const currentValue = this.system.abilities[ability].value;
            const newValue = currentValue + 1;

            await this.update({
              [`system.abilities.${ability}.value`]: newValue,
              'system.attributes.statIncreases': available - 1
            });

            ui.notifications.info(`${ability.toUpperCase()} increased to ${newValue}!`);

            // Prompt again if more increases are available
            if (available > 1) {
              setTimeout(() => this.promptStatIncrease(), 500);
            }
          }
        },
        cancel: {
          icon: '<i class="fas fa-times"></i>',
          label: "Later"
        }
      },
      default: "increase"
    }).render(true);
  }

  /**
   * Grant stat increases (typically on level up)
   * @param {number} amount - Number of stat increases to grant
   */
  async grantStatIncreases(amount = 1) {
    if (this.type !== 'character') return;

    const current = this.system.attributes.statIncreases || 0;
    await this.update({ 'system.attributes.statIncreases': current + amount });

    ui.notifications.info(`Gained ${amount} stat increase${amount > 1 ? 's' : ''}!`);

    // Auto-prompt if they want to spend it now
    setTimeout(() => {
      new Dialog({
        title: "Stat Increases Available",
        content: `<p>You have stat increases available. Would you like to spend them now?</p>`,
        buttons: {
          yes: {
            label: "Yes",
            callback: () => this.promptStatIncrease()
          },
          no: {
            label: "Later"
          }
        },
        default: "yes"
      }).render(true);
    }, 500);
  }

  /**
   * Award failure XP to this character
   * @param {number} amount - Amount of XP to award
   * @private
   */
  async _awardFailureXP(amount) {
    if (this.type !== 'character') return;

    const currentXP = this.system.attributes.failureXP || 0;
    const newXP = currentXP + amount;

    await this.update({ 'system.attributes.failureXP': newXP });
    ui.notifications.info(`+${amount} Failure XP! (Total: ${newXP})`);
  }

  /**
   * Spend failure XP to turn dice into 6s for skill improvement
   * @param {number} numDice - Number of dice to convert to 6s
   * @returns {boolean} Whether the XP was successfully spent
   */
  async spendFailureXP(numDice) {
    if (this.type !== 'character') return false;

    const currentXP = this.system.attributes.failureXP || 0;
    const cost = numDice; // 1 XP per die

    if (currentXP < cost) {
      ui.notifications.warn(`Not enough Failure XP! Need ${cost}, have ${currentXP}.`);
      return false;
    }

    await this.update({ 'system.attributes.failureXP': currentXP - cost });
    ui.notifications.info(`Spent ${cost} Failure XP. (Remaining: ${currentXP - cost})`);
    return true;
  }

  /**
   * Award character-level XP (see Rules/Character Leveling.md) for defeating a threat or
   * overcoming a challenge. Distinct from Failure XP - this is what attributes.xp.value
   * tracks toward the 300*level threshold. Does not auto-level; the Level Up button stays
   * a deliberate, separate action once enough XP is banked.
   * @param {number} amount - Amount of XP to award
   */
  async addXP(amount) {
    if (this.type !== 'character') return;

    const currentXP = this.system.attributes.xp.value || 0;
    const newXP = currentXP + amount;

    await this.update({ 'system.attributes.xp.value': newXP });
    ui.notifications.info(`${this.name} gains ${amount} XP! (${newXP}/${this.system.attributes.xp.max})`);

    if (newXP >= this.system.attributes.xp.max) {
      ui.notifications.info(`${this.name} has enough XP to level up!`);
    }
  }

  /**
   * GM-facing prompt to award XP to this character.
   */
  async promptAwardXP() {
    if (this.type !== 'character') return;

    new Dialog({
      title: `Award XP to ${this.name}`,
      content: `
        <form>
          <div class="form-group">
            <label>XP Amount:</label>
            <input type="number" name="amount" value="50" autofocus />
          </div>
        </form>
      `,
      buttons: {
        award: {
          icon: '<i class="fas fa-star"></i>',
          label: "Award",
          callback: async (html) => {
            const amount = parseInt(html[0].querySelector('input[name="amount"]').value) || 0;
            if (amount > 0) await this.addXP(amount);
          }
        },
        cancel: {
          icon: '<i class="fas fa-times"></i>',
          label: "Cancel"
        }
      },
      default: "award"
    }).render(true);
  }

  /**
   * Roll a spell check for this actor
   * @param {string} itemId - The ID of the spell item to roll
   * @param {Object} options - Additional options for the roll
   * @returns {Promise<Object>} The roll result
   */
  async rollSpell(itemId, options = {}) {
    const spell = this.items.get(itemId);
    if (!spell) {
      ui.notifications.error(`Spell "${itemId}" not found.`);
      return null;
    }

    // Check if character has enough mana
    const prowessCost = spell.system.prowess || 0;
    if (prowessCost > 0 && this.system.mana.value < prowessCost) {
      ui.notifications.warn(`Not enough mana! Need ${prowessCost}, have ${this.system.mana.value}.`);
      return null;
    }

    const diceCount = spell.system.diceCount || 1;
    // LUK applies to every roll, cast stat modifier on top of that if the spell has one.
    let statModifier = this.system.luck?.total || 0;

    if (spell.system.castStat && this.system.abilities[spell.system.castStat]) {
      statModifier += this.system.abilities[spell.system.castStat].mod || 0;
    }

    const rollResult = await rollSkillCheck({
      skillLevel: diceCount,
      statModifier,
      skillName: spell.name,
      actor: this
    });

    // Deduct mana after successful cast
    if (prowessCost > 0) {
      const newMana = Math.max(0, this.system.mana.value - prowessCost);
      await this.update({ 'system.mana.value': newMana });
      ui.notifications.info(`-${prowessCost} Mana (${newMana}/${this.system.mana.max})`);
    }

    // Send to chat unless explicitly disabled
    if (options.sendToChat !== false) {
      await sendSkillRollToChat(rollResult, {
        ...options.chatOptions,
        offensiveSpell: spell.system.offensive ? { id: spell.id, name: spell.name } : null
      });
    }

    // Check for spell improvement (all 6s)
    if (rollResult.allSixes && options.checkImprovement !== false) {
      await this._promptSpellImprovement(spell);
    }

    return rollResult;
  }

  /**
   * Prompt the user about spell improvement
   * @param {Item} spell - The spell item that can be improved
   * @private
   */
  async _promptSpellImprovement(spell) {
    const currentDiceCount = spell.system.diceCount || 1;

    new Dialog({
      title: "⚡ Spell Mastery!",
      content: `
        <p>You rolled all 6s with <strong>${spell.name}</strong> (${currentDiceCount}d6)!</p>
        <p>Your understanding of this spell deepens. Increase its power?</p>
      `,
      buttons: {
        improve: {
          icon: '<i class="fas fa-arrow-up"></i>',
          label: "Improve Spell",
          callback: async () => {
            await spell.update({ 'system.diceCount': currentDiceCount + 1 });
            ui.notifications.info(`⚡ ${spell.name} improved to ${currentDiceCount + 1}d6!`);
          }
        },
        cancel: {
          icon: '<i class="fas fa-times"></i>',
          label: "Later"
        }
      },
      default: "improve"
    }).render(true);
  }

  /**
   * Regenerate missing HP/Stamina/Mana at the start of this character's turn.
   * See Rules/Resources/{Health,Stamina,Mana} Points.md.
   * @returns {Promise<Array|null>} Regen results per resource
   */
  async regenResources() {
    return rollResourceRegen(this);
  }

  /**
   * Open lootboxes of a given tier, pulling random loot from the Items & Equipment and
   * Weapons compendium packs (see module/helpers/lootbox.mjs).
   * @param {string} tier - One of CONFIG.DCC_WORLD.lootboxTiers
   * @param {number} count - How many to open; clamped to how many are actually owned.
   * @returns {Promise<Array|null>} The looted results
   */
  async openLootboxTier(tier, count = 1) {
    return openLootboxTier(this, tier, count);
  }

  /**
   * Roll a weapon attack for this actor
   * @param {string} itemId - The ID of the weapon item to roll
   * @param {Object} options - Additional options for the roll
   * @returns {Promise<Object>} The roll result
   */
  async rollWeapon(itemId, options = {}) {
    const weapon = this.items.get(itemId);
    if (!weapon || weapon.type !== 'weapon') {
      ui.notifications.error(`Weapon "${itemId}" not found.`);
      return null;
    }

    // Check if weapon is equipped
    if (!weapon.system.equipped) {
      ui.notifications.warn(`${weapon.name} is not equipped!`);
      return null;
    }

    // Get granted skills
    const grantedSkills = weapon.system.grantedSkills || [];
    if (grantedSkills.length === 0) {
      ui.notifications.warn(`${weapon.name} has no combat skills!`);
      return null;
    }

    // For each granted skill, get the character's actual skill level
    const availableSkills = [];
    for (const grantedSkill of grantedSkills) {
      const skill = this.system.getSkill(grantedSkill.skillUuid);
      if (skill && skill.level > 0) {
        availableSkills.push({
          uuid: grantedSkill.skillUuid,
          name: skill.name,
          maxLevel: skill.level,
          category: skill.category
        });
      }
    }

    if (availableSkills.length === 0) {
      ui.notifications.warn(`You don't have any of the required skills for ${weapon.name}!`);
      return null;
    }

    // Calculate total effort from all equipped weapons for each skill
    const allEquippedWeapons = this.items.filter(i => i.type === 'weapon' && i.system?.equipped === true);
    const skillEffortMap = {};

    for (const skill of availableSkills) {
      let totalEffort = 0;
      for (const w of allEquippedWeapons) {
        const weaponSkills = w.system?.grantedSkills || [];
        if (weaponSkills.some(gs => gs.skillUuid === skill.uuid)) {
          totalEffort += (w.system?.effort || 0);
        }
      }
      skillEffortMap[skill.uuid] = totalEffort;
    }

    // Show dialog to select skill and level
    return new Promise((resolve) => {
      new Dialog({
        title: `Attack with ${weapon.name}`,
        content: `
          <form>
            <div class="form-group">
              <label>Combat Skill:</label>
              <select name="skillUuid" autofocus>
                ${availableSkills.map(s => `<option value="${s.uuid}">${s.name} (Level ${s.maxLevel})</option>`).join('')}
              </select>
            </div>
            <div class="form-group">
              <label>Skill Level to Roll:</label>
              <select name="skillLevel" id="skill-level-select">
                ${availableSkills[0] ? Array.from({length: availableSkills[0].maxLevel}, (_, i) => i + 1)
                  .map(lvl => `<option value="${lvl}" ${lvl === availableSkills[0].maxLevel ? 'selected' : ''}>${lvl}d6</option>`).join('') : ''}
              </select>
            </div>
            <div class="form-group">
              <p><strong>Weapon:</strong> ${weapon.name} (${weapon.system.rarity})</p>
              <p><strong>Total Equipped Weapon Effort:</strong> <span id="weapon-effort">${skillEffortMap[availableSkills[0]?.uuid] || 0}</span></p>
              <p><strong>Stamina Cost:</strong> <span id="stamina-cost">${(skillEffortMap[availableSkills[0]?.uuid] || 0) * (availableSkills[0]?.maxLevel || 1)}</span></p>
              <p class="notes">Cost = Total Equipped Weapon Effort × Skill Level</p>
            </div>
          </form>
          <script>
            const skillEfforts = ${JSON.stringify(skillEffortMap)};
            document.querySelector('select[name="skillUuid"]').addEventListener('change', (e) => {
              const skillUuid = e.target.value;
              const skill = ${JSON.stringify(availableSkills)}.find(s => s.uuid === skillUuid);
              const levelSelect = document.getElementById('skill-level-select');
              levelSelect.innerHTML = '';
              for (let i = 1; i <= skill.maxLevel; i++) {
                const option = document.createElement('option');
                option.value = i;
                option.text = i + 'd6';
                if (i === skill.maxLevel) option.selected = true;
                levelSelect.appendChild(option);
              }
              document.getElementById('weapon-effort').textContent = skillEfforts[skillUuid] || 0;
              updateStaminaCost();
            });
            document.getElementById('skill-level-select').addEventListener('change', updateStaminaCost);
            function updateStaminaCost() {
              const skillUuid = document.querySelector('select[name="skillUuid"]').value;
              const level = parseInt(document.getElementById('skill-level-select').value);
              const effort = skillEfforts[skillUuid] || 0;
              const cost = effort * level;
              document.getElementById('stamina-cost').textContent = cost;
            }
          </script>
        `,
        buttons: {
          attack: {
            icon: '<i class="fas fa-dice-d20"></i>',
            label: "Attack",
            callback: async (html) => {
              const formData = new FormData(html[0].querySelector('form'));
              const skillUuid = formData.get('skillUuid');
              const skillLevel = parseInt(formData.get('skillLevel'));

              // Roll the skill (effort cost will be calculated automatically from equipped weapons)
              const result = await this.rollSkill(skillUuid, {
                customLevel: skillLevel,
                sendToChat: true,
                checkImprovement: true
              });

              resolve(result);
            }
          },
          cancel: {
            icon: '<i class="fas fa-times"></i>',
            label: "Cancel",
            callback: () => resolve(null)
          }
        },
        default: "attack"
      }).render(true);
    });
  }

}
